### ISSUE TITLE
It works!

### ISSUE THREAD

**Issue by stefan-reich** [nwaldispuehl/java-lame#10]
I use issues to communicate because many developers don't read anything else... :)

Just saying the library works great. [Integrated](http://tinybrain.de/1019665) into my language JavaX.

I use it to make MP3s for wit.ai (speech recognition) in my [OS](http://BotCompany.de).

BTW what's the default bit rate?

Cheers

![Screenshot](http://ai1.space/1004590/raw/1101422)

**Comment by nwaldispuehl** [comment]
Great!

Default bit rate according to the `net.sourceforge.lame.mp3.LameGlobalFlags` class:
```
  /**
   * bit rate (constant bit rate).
   * <p/>
   * Note: set either bit rate>0 or compression ratio>0, LAME will compute the
   * value of the variable not set. Default is compression_ratio = 11.025
   */
  private int bitRate;
```
