### ISSUE TITLE
Decoding example missing

### ISSUE THREAD

**Issue by paulorrfilho** [nwaldispuehl/java-lame#13]
Hi, thank you very much for putting this library together!
I was able to use java-lame to encode the pcm data generated by my app.
Now I would like to decode it back to pcm. Would it be possible to provide some guidance on how to decode an mp3 file? I am struggling to understand how to use the `decode(ByteBuffer sampleBuffer)` function provided by the `LameDecoder`.
Not sure if I need to iterate through the samples like the encode one.

I tried the below but the `ByteArray` has only zeros. I guess I am missing a lot here.

```
  val file = File(Environment.getExternalStorageDirectory().toString() + "/" + File.separator + "dk_mp3_from_pcm.mp3")

  val decoder = LameDecoder(file.path)

  var byteBuf : ByteBuffer = ByteBuffer.allocate(1000000)
  decoder.decode(byteBuf)
  decoder.close()
  for (byte in byteBuf.array()) {
       Log.d("pwd DK", "pwd byte $byte")
  }

**Comment by nwaldispuehl** [comment]
Hi Paulo,
thanks for getting in touch! 

I will enhance this sample unit test by a decoding example soon. The decoding is easily done, but you end up with raw PCM byte array:
```
    LameDecoder decoder = new LameDecoder(mp3File.getAbsolutePath());

    ByteBuffer buffer = ByteBuffer.allocate(decoder.getBufferSize());
    ByteArrayOutputStream pcm = new ByteArrayOutputStream();

    while (decoder.decode(buffer)) {
      pcm.write(buffer.array());
    }

    return pcm.toByteArray();
```
For my example test the data should be stored as WAV file, so I need to add the WAV headers etc. in some easy, portable way.

**Comment by paulorrfilho** [comment]
Thank you
