### ISSUE TITLE
Add stopDecoder function

### ISSUE THREAD

**Issue by paulorrfilho** [nwaldispuehl/java-lame#15]
It would be nice to have a function to stop the decoding process somehow.
I am facing this issue right now.
Use case: User starts playing a song (which could take up to 15 seconds to finish decoding on Android), then chooses a different song a few seconds later.
`decoder.close()` does not seem to do much in this case.

**Comment by nwaldispuehl** [comment]
Hi Paulo,
thank you for your inquiry. This is not the task of a decoder; it only takes a chunk of data and converts it into another format.
Your implementation has to make sure that this decoding process is being interrupted; in the example of the `LameDecoderTest`:

```
    while (decoder.decode(buffer)) {
      pcm.write(buffer.array());
    }
```
some mechanism could be put in place which can stop the loop at your command, e.g.:

```
   boolean active = true;
    while (decoder.decode(buffer) && active) {
      pcm.write(buffer.array());
    }
```
with a method:
```
public void stopDecoder() {
    active = false;
}
```

**Comment by nwaldispuehl** [comment]
Besides: If you're on the Android platform, I believe you wouldn't need this library to decode MP3; the `MediaPlayer` etc. can do this on their own.

**Comment by paulorrfilho** [comment]
Thanks @nwaldispuehl  - I had to go with a workaround where I have to keep the decoders in a dictionary where I activate/deactivate them.
I am porting my drum app from iOS so I need a low latency stream, for this reason, I cannot use the `MediaPlayer` class, that's why I need to decode the mp3s myself so I can record them later on my own audio stream.

sorry to keep bothering you with my requests ;)

**Comment by nwaldispuehl** [comment]
Why not just ship the app with the raw pcm data; or compute it on first start of the app or something? Storage is cheap, computation is expensive, especially in a smartphone app.

**Comment by paulorrfilho** [comment]
I am using it to decode the user's mp3 files to play along, not the drum sounds, so it has to be done in real-time.
I think I am going to use the MediaCodec provided by Android to decode the mp3 files and use java-lame to encode only.
