### ISSUE TITLE
Only hear the noise, the other can not hear

### ISSUE THREAD

**Issue by chinavane** [nwaldispuehl/java-lame#2]
I tried a demo example, want a pcm files into mp3 files, but to convert mp3 files only after the noise, the other could hear nothing, which is why? I think the main AudioFormat a problem here, but could not find the reason, we hope to help answer it.

package test;

import java.io.ByteArrayOutputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.nio.file.Path;
import java.nio.file.Paths;

import javax.sound.sampled.AudioFormat;

import net.sourceforge.lame.lowlevel.LameDecoder;
import net.sourceforge.lame.lowlevel.LameEncoder;
import net.sourceforge.lame.mp3.Lame;
import net.sourceforge.lame.mp3.MPEGMode;

public class main {

	public static byte[] encodePcmToMp3(byte[] pcm) throws IOException {

		AudioFormat inputFormat = new AudioFormat(16000, 16, 2, true, true);
		LameEncoder encoder = new LameEncoder(inputFormat, 256,
				MPEGMode.STEREO, Lame.QUALITY_HIGHEST, false);

		ByteArrayOutputStream mp3 = new ByteArrayOutputStream();
		byte[] buffer = new byte[encoder.getPCMBufferSize()];

		int bytesToTransfer = Math.min(buffer.length, pcm.length);
		int bytesWritten;
		int currentPcmPosition = 0;
		while (0 < (bytesWritten = encoder.encodeBuffer(pcm,
				currentPcmPosition, bytesToTransfer, buffer))) {
			currentPcmPosition += bytesToTransfer;
			bytesToTransfer = Math.min(buffer.length, pcm.length
					- currentPcmPosition);
			mp3.write(buffer, 0, bytesWritten);
		}

		FileOutputStream outStream = new FileOutputStream(
				"/Users/vane/Documents/workspace/test/test.mp3");
		mp3.writeTo(outStream);

		encoder.close();
		return mp3.toByteArray();
	}

	public static void main(String[] args) throws IOException {
		String fileLocation = "/Users/vane/Documents/workspace/test/test.pcm";
		Path path = Paths.get(fileLocation);
		byte[] fileInBytes = java.nio.file.Files.readAllBytes(path);
		encodePcmToMp3(fileInBytes);
	}
}

**Comment by chinavane** [comment]
input:  /Users/vane/Documents/workspace/test/test.pcm
	(11.0250 kHz, 2 channels, MPEG-1 Layer III)
output: (16 bit, Microsoft WAVE)
skipping initial 1105 samples (encoder+decoder delay)

**Comment by nwaldispuehl** [comment]
Hi chinavane, sorry for the late answer.
Does the problem still persist, or is it still a topic?
Kind regards

**Comment by nwaldispuehl** [comment]
Doesn't seem to be a topic anymore.
