### ISSUE TITLE
can't run in android system

### ISSUE THREAD

**Issue by chinavane** [nwaldispuehl/java-lame#3]
I want to run this method on android system, but it does not support the current classes javax.sound.sampled, but is limited to android.media, so when you run LameEncoder method, whether modified to also be able to javax.soud.sampled support android.media it?

**Comment by nwaldispuehl** [comment]
Hi chinavane, sorry for the late answer.
Does the problem still persist, or is it still a topic?

As far as I can see you could remove the `javax.sound.sampled.AudioFormat` from the class `LameEncoder` by passing the single properties, its just convenience.

Kind regards

**Comment by nwaldispuehl** [comment]
Anyway, its more like a general Java issue than one with lame, so I'm closing this one.
