### ISSUE TITLE
java.lang.NegativeArraySizeException decoding Mp3

### ISSUE THREAD

**Issue by octaviospain** [nwaldispuehl/java-lame#4]
Hi, I'm trying to get the byte array from an Mp3 in order to obtain the amplitudes, to plot the waveform of the audio. To do so I'm using java-lame in the way that is described in the README.md:

```java
AudioInputStream audioInputStream = AudioSystem.getAudioInputStream(file);
AudioFormat baseFormat = audioInputStream.getFormat();
byte[] PCMArray = new byte[audioInputStream.available()];
int numReadBytes = audioInputStream.read(PCMArray);
byte[] decodedBytes = encodePcmToMp3(baseFormat, PCMArray);

private byte[] encodePcmToMp3(AudioFormat inputFormat, byte[] pcm) {
		  LameEncoder encoder = new LameEncoder(inputFormat, 320, MPEGMode.STEREO, Lame.QUALITY_HIGHEST, false);
		  ByteArrayOutputStream mp3 = new ByteArrayOutputStream();
		  byte[] buffer = new byte[encoder.getPCMBufferSize()];

		  int bytesToTransfer = Math.min(buffer.length, pcm.length);
		  int bytesWritten;
		  int currentPcmPosition = 0;
		  while (0 < (bytesWritten = encoder.encodeBuffer(pcm, currentPcmPosition, bytesToTransfer, buffer))) {
		    currentPcmPosition += bytesToTransfer;
		    bytesToTransfer = Math.min(buffer.length, pcm.length - currentPcmPosition);

		    mp3.write(buffer, 0, bytesWritten);
		  }

		  encoder.close();
		  return mp3.toByteArray();
		}
```

but It throws me an  `java.lang.NegativeArraySizeException`:
```
at net.sourceforge.lame.lowlevel.LameEncoder.doEncodeBuffer(LameEncoder.java:228)
at net.sourceforge.lame.lowlevel.LameEncoder.encodeBuffer(LameEncoder.java:304)
```

can anyone help me with this? Thanks in advance

**Comment by nwaldispuehl** [comment]
Hi octaviospain, sorry for the late answer.
Does the problem still persist, or is it still a topic?
Kind regards

**Comment by octaviospain** [comment]
Still persist. Can you reproduce the code and check please?

**Comment by nwaldispuehl** [comment]
I ran your example and it worked flawless with such input file:

    short.wav: RIFF (little-endian) data, WAVE audio, Microsoft PCM, 16 bit, stereo 44100 Hz 

with this Java version:

    java version "1.8.0_60"
    Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
    Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)


If we inspect `LameEncoder.java:228`:

    int bytesPerSample = sampleSizeInBits >> 3;
    int samplesRead = length / bytesPerSample;
    int[] sampleBuffer = new int[samplesRead]; // line 228

we see that the negative sized array can only occur if either the `length` or the `bytesPerSample` value is negative. The latter can get negative if the `sampleSizeInBits` is negative. 

A bit above it is determined as follows:

    sampleSizeInBits = sourceFormat.getSampleSizeInBits();

Maybe check your input file. I recall such values being `-1` if they can't be determined or something, so also check your javax.sound implementation. You're using Oracle Java?

**Comment by nwaldispuehl** [comment]
Ah, I was only now actually reading the text in your entry where it states:

> trying to get the byte array from an Mp3 

Java-Lame is a MP3-**Encoder**, it expects PCM audio as input. To decode MP3 use for example the http://www.javazoom.net/ library.
