### ISSUE TITLE
progress listener stops at 80%

### ISSUE THREAD

**Issue by olze** [nwaldispuehl/java-lame#6]
the file is converted correctly, but the progress stops at 80%

https://github.com/olze/volvomp3 is a little project which shows the problem

**Comment by nwaldispuehl** [comment]
Hi Olze,
thank you for your inquiry.

This 'progress listener' apparently was not intended for precise percentages, but only for a coarse progress indication. I did a little change which should let it produce more accurate numbers.

An alternative would be to use the ```LameEncoder```class of the original author - Ken Händel as proposed in the projects README file: https://github.com/nwaldispuehl/java-lame/blob/master/README.md
There you have the byte array sizes in your hand and can easily intercept the progress. See its use in one of my other projects as example: 

https://github.com/nwaldispuehl/interval-music-compositor/blob/master/intervalmusiccompositor.encoder.mp3/src/main/java/ch/retorte/intervalmusiccompositor/encoder/LameByteArrayEncoder.java#L40
