### ISSUE TITLE
LameEncoder Variable Bitrate

### ISSUE THREAD

**Issue by jvtrigueros** [nwaldispuehl/java-lame#9]
Hey Olze,

I know you just took the port of the MP3 encoding code as is, but I just want to see if you have seen this behaviour. I'm setting the `LameEncoder` setting for VBR to `true` but when I play the audio back, it works up to some point and then the player goes bonkers.

Have you seen this behaviour? Or is my code wrong?

-jvt

**Comment by nwaldispuehl** [comment]
Hi jvt,

I've never tried it with VBR. If the same code works with VBR = `false`, i.e. constant bit rate (CBR), then the wrong appears to be not your code but the VBR functionality of the library conversion.

Cheers
Nico

**Comment by jvtrigueros** [comment]
Actually, I did some searching around and it sounds like this is a prominent issue with MP3 encoding and VBR. Seek get's all messed up until you run some corrective action. Looking into that now, I will share the solution if I find any.
